title: Marco G. Portfolio
description:  Marco G. Portfolio
author: Marco G.
markdown: kramdown
highlighter: rouge
url: "https://pnguinmster.github.io"
baseurl: "/portfolio-pages"
defaults: 
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog_pages/:title
